import TopMenu from "@/app/_components/TopMenu";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-100 w-screen`}>
        <TopMenu />
        <div className="container max-w-screen-xl mx-auto px-4">{children}</div>
      </body>
    </html>
  );
}
